import { Component } from '@angular/core';

@Component({
  selector: 'app-card-template2',
  templateUrl: './card-template2.component.html',
  styleUrls: ['./card-template2.component.scss'],
})
export class CardTemplate2Component {
  currentRate = 3;
  data = [
    {
      id: '1',
      src: './assets/images/media/pictures/1.jpg',
      price: '$35',
      title: 'HTML Template',
      details: 'View Details',
      preview: 'Live preview',
      like: '364',
      download: '29',
      name: 'Emily Parsons',
      sale: '45',
      tag: 'HTML',
      summary: 'HTML Template',
      btn2: 'Add to cart',
      btn1: 'Buy Now',
    },
    {
      id: '2',
      src: './assets/images/media/pictures/3.jpg',
      price: '$24',
      title: 'PSD Template',
      details: 'View Details',
      preview: 'Live preview',
      like: '368',
      download: '25',
      name: 'john ',
      sale: '25',
      tag: 'PSD',
      summary: 'PSD Template',
      btn2: 'Add to cart',
      btn1: 'Buy Now',
    },
    {
      id: '3',
      tag: 'Angular',
      src: './assets/images/media/pictures/4.jpg',
      price: '$47',
      title: 'Angular Template',
      details: 'View Details',
      preview: 'Live preview',
      like: '457',
      download: '64',
      summary: 'Angular Template',
      btn2: 'Add to cart',
      btn1: 'Buy Now',
      name: 'Jessica Turner',
      sale: '20',
    },
    {
      id: '4',
      tag: 'PHP',
      src: './assets/images/media/pictures/5.jpg',
      price: '$25',
      title: 'PHP Template',
      details: 'View Details',
      preview: 'Live preview',
      like: '154',
      download: '15',
      summary: 'PHP Template',
      btn2: 'Add to cart',
      btn1: 'Buy Now',

      name: 'Joss Butler',
      sale: '27',
    },
    {
      id: '5',
      tag: 'Wordpress',
      src: './assets/images/media/pictures/7.jpg',
      price: '$34',
      title: 'Wordpress Template',
      details: 'View Details',
      preview: 'Live preview',
      like: '325',
      download: '35',
      summary: 'Wordpress Template',
      btn2: 'Add to cart',
      btn1: 'Buy Now',
      name: 'Anna Howard',
      sale: '17',
    },
    {
      id: '6',
      tag: 'GPR HTML',
      src: './assets/images/media/pictures/6.jpg',
      price: '$41',
      title: 'GPR HTML Template',
      details: 'View Details',
      preview: 'Live preview',
      like: '452',
      download: '45',
      summary: 'GPR HTML Template',
      btn2: 'Add to cart',
      btn1: 'Buy Now',
      name: 'Eric Russell',
      sale: '29',
    },
  ];
}
