import { Component } from '@angular/core';

@Component({
  selector: 'app-table2',
  templateUrl: './table2.component.html',
  styleUrls: ['./table2.component.scss'],
})
export class Table2Component {
  currentRate = 5;
  data = [
    {
      src: './assets/images/png/1.png',
      name: 'Marco Theme',
      tag1: './assets/images/png/10.png',
      tag2: './assets/images/png/11.png',
      tag3: './assets/images/png/12.png',
      item: '154',
      follower: '84',
      date: 'June 2017',
      sales: '741',
      rating: '',
    },
    {
      src: './assets/images/png/2.png',
      name: 'Lisa Theme',
      tag1: './assets/images/png/10.png',
      tag2: './assets/images/png/11.png',
      tag3: './assets/images/png/12.png',
      item: '215',
      follower: '56',
      date: 'Jan 2019',
      sales: '658',
      rating: '',
    },
    {
      src: './assets/images/png/3.png',
      name: 'Marshall Theme',
      tag1: './assets/images/png/10.png',
      tag2: './assets/images/png/11.png',
      tag3: './assets/images/png/12.png',
      item: '254',
      follower: '89',
      date: 'May 2017',
      sales: '684',
      rating: '',
    },
    {
      src: './assets/images/png/4.png',
      name: 'Chapman Theme',
      tag1: './assets/images/png/10.png',
      tag2: './assets/images/png/11.png',
      tag3: './assets/images/png/12.png',
      item: '154',
      follower: '57',
      date: 'Jan 2019',
      sales: '358',
      rating: '',
    },
    {
      src: './assets/images/png/5.png',
      name: 'Robic Theme',
      tag1: './assets/images/png/10.png',
      tag2: './assets/images/png/11.png',
      tag3: './assets/images/png/12.png',
      item: '125',
      follower: '89',
      date: 'June 2017',
      sales: '584',
      rating: '',
    },
    {
      src: './assets/images/png/3.png',
      name: 'Hymbo Theme',
      tag1: './assets/images/png/10.png',
      tag2: './assets/images/png/11.png',
      tag3: './assets/images/png/12.png',
      item: '145',
      follower: '76',
      date: 'Aug 2018',
      sales: '586',
      rating: '',
    },
    {
      src: './assets/images/png/5.png',
      name: 'Cmaho  Theme',
      tag1: './assets/images/png/10.png',
      tag2: './assets/images/png/11.png',
      tag3: './assets/images/png/12.png',
      item: '187',
      follower: '58',
      date: 'May 2017',
      sales: '657',
      rating: '',
    },
  ];
}
